#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ledger_check.py — TRELLIS-010 Research-Traceability validator + index emitter
(spec: Plan/TRELLIS-010_LEDGER.md CLAIM-0011 · existence+consistency เท่านั้น · ไม่ตัดสิน semantics · fail-loud)

สองโหมด (แยก invocation กัน self-grading · doctrine "Verify ≠ self-grading"):
  --emit-index      สแกน disk → พิมพ์ SCRIPT INDEX skeleton (ASSET=import-scan · EXPERIMENT=__main__)
                    · คนเติม disposition+Claim-ID ลง skeleton แล้ว paste เข้า LEDGER
  (default)         validate LEDGER.md เทียบ disk **สด** (re-derive ตอน commit) → regression guard
  --self-test       รัน self-test (fixtures + golden · จำนวน = ดู output ไม่ hardcode) (pin scan-logic อิสระจาก emit)

checks: (a) cover (b) reproduce-resolves (c) required-fields (d) frontier/carried ref
        (e) script→claim + claim-internal Claim-ID ref (f) __main__→EXPERIMENT (g) imported→ASSET
        (h) non-live claim cited ใน frontier ต้องมี annotation (→/DEAD/=live · กัน bare superseded-cite)
        (i) superseded cite arrow-target ต้องตรง status-target (SSOT=status · กัน denorm-without-sync)
        (j) status ต้องขึ้นต้นด้วย disposition token + superseded ต้องมี →target (enforce P4 · กัน silent false-negative)
"""
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
LEDGER = ROOT.parent / "Plan" / "TRELLIS-010_LEDGER.md"
MAIN_RE = re.compile(r"if\s+__name__\s*==\s*['\"]__main__['\"]")
CLAIMID_RE = re.compile(r"CLAIM-\d{4}")
# จับทั้ง 2 spelling ของ status-target · re.I ให้ consistent กับ gate ที่เช็คบน lowered (MINOR-3)
SUP_TGT = re.compile(r"superseded(?:→|-by-)CLAIM-(\d{4})", re.I)
# disposition-token vocabulary — `status:` ต้องขึ้นต้นด้วย token ใดตัวหนึ่ง (บังคับโดย check j)
# token ใหม่ในอนาคต = เพิ่ม tuple ที่นี่ (fail-loud by design) · NONLIVE = subset ที่ (h) ใช้
NONLIVE = ("superseded", "dead", "falsified", "inconclusive")
STATUS_TOKENS = ("live", "terminal") + NONLIVE
TOKEN_RE = re.compile(r"^(" + "|".join(STATUS_TOKENS) + r")\b")


def leading_token(st):
    """จุด parse เดียวของ disposition token (single parser — กัน predicate-drift ระหว่าง check h/i/j)"""
    m = TOKEN_RE.match(st.strip().lower())
    return m.group(1) if m else None
REQUIRED = ["observed", "supported", "not-yet-supported", "evidence-level",
            "dependencies", "invalidated-by", "kind", "status", "fairness",
            "correction-lineage", "scope-of-death", "reproduce"]


def scan(scripts_dir):
    """ground-truth จาก disk: (imported_by, has_main) ต่อ module · ast = robust (จับ import a,b / func-level)"""
    files = sorted(p.stem for p in scripts_dir.glob("*.py"))
    fset = set(files)
    imported_by = {f: set() for f in files}
    has_main = set()
    for p in scripts_dir.glob("*.py"):
        mod, src = p.stem, p.read_text(encoding="utf-8", errors="replace")
        if MAIN_RE.search(src):
            has_main.add(mod)
        try:
            tree = ast.parse(src)
        except SyntaxError as e:
            fail(f"parse {mod}: {e}")
        for n in ast.walk(tree):
            if isinstance(n, ast.Import):
                for a in n.names:
                    b = a.name.split(".")[0]
                    if b in fset and b != mod:
                        imported_by[b].add(mod)
            elif isinstance(n, ast.ImportFrom) and n.level == 0 and n.module:
                b = n.module.split(".")[0]
                if b in fset and b != mod:
                    imported_by[b].add(mod)
    return files, imported_by, has_main


def emit_index(scripts_dir):
    """skeleton machine-generated · role มาจาก disk-signal ไม่ใช่ hand-list (DEFECT-10)"""
    files, imported_by, has_main = scan(scripts_dir)
    out = ["## SCRIPT INDEX", "> generated by `ledger_check.py --emit-index` · role=disk-signal · เติม <DISP> เอง",
           "> DISP ∈ live→CLAIM-NNNN | superseded→CLAIM-NNNN | legacy→ARCHIVE | reproduce-only(why) | self-test(why)", ""]
    for f in files:
        tags = []
        if imported_by[f]:
            tags.append(f"ASSET(imported {len(imported_by[f])})")
        if f in has_main:
            tags.append("EXPERIMENT=<DISP>")
        out.append(f"- `{f}` :: " + " :: ".join(tags))
    return "\n".join(out)


def parse_ledger(text):
    """แยก SCRIPT-INDEX rows · CLAIM blocks · frontier/carried refs — parse-only ไม่ตัดสิน"""
    index = {}   # name -> {"asset":bool, "exp":disp-or-None, "claim":CLAIM-or-None}
    for m in re.finditer(r"^-\s+`([A-Za-z_]\w*)`\s*::\s*(.+)$", text, re.M):
        name, tail = m.group(1), m.group(2)
        disp = None
        em = re.search(r"EXPERIMENT=([^\s:]+(?:\([^)]*\))?)", tail)
        if em:
            disp = em.group(1)
        cm = CLAIMID_RE.search(tail)
        index[name] = {"asset": "ASSET" in tail, "exp": disp,
                       "claim": cm.group(0) if cm else None}
    claims = {}  # CLAIM-NNNN -> {field: value}
    for cm in re.finditer(r"^###\s+(CLAIM-\d{4})\s*$(.*?)(?=^###\s+CLAIM-\d{4}|\Z)", text, re.M | re.S):
        cid, body = cm.group(1), cm.group(2)
        fields = {}
        for fm in re.finditer(r"^-\s+\*\*([a-z\-]+):\*\*\s*(.*)$", body, re.M):
            fields[fm.group(1)] = fm.group(2).strip()
        claims[cid] = fields
    # frontier + carried = Claim-IDs อ้างในสอง section (ก่อน ## SCRIPT INDEX)
    head = text.split("## SCRIPT INDEX")[0]
    fc_refs = set(CLAIMID_RE.findall(head))
    return index, claims, fc_refs


ERRORS = []


def fail(msg):
    ERRORS.append(msg)


def validate(scripts_dir, ledger_path):
    if not ledger_path.exists():
        fail(f"LEDGER not found: {ledger_path}")
        return
    files, imported_by, has_main = scan(scripts_dir)
    text = ledger_path.read_text(encoding="utf-8", errors="replace")
    index, claims, fc_refs = parse_ledger(text)
    diskset, idxset = set(files), set(index)
    # (a) cover — ทุกไฟล์ disk ปรากฏใน index ≥1 role
    for f in diskset - idxset:
        fail(f"(a) cover: `{f}` บน disk แต่ไม่มีใน SCRIPT INDEX")
    for f in idxset - diskset:
        fail(f"(a) cover: `{f}` ใน INDEX แต่ไม่มีบน disk (stale)")
    for f in idxset & diskset:
        if not index[f]["asset"] and not index[f]["exp"]:
            fail(f"(a) cover: `{f}` ไม่มี role ใด (ต้อง ASSET หรือ EXPERIMENT)")
    # (f) __main__ → ต้องมี EXPERIMENT disposition
    for f in has_main & idxset:
        if not index[f]["exp"]:
            fail(f"(f) `{f}` มี __main__ แต่ไม่มี EXPERIMENT disposition (ซ่อน experiment)")
    # (g) imported → ต้องมี ASSET role
    for f in idxset:
        if imported_by.get(f) and not index[f]["asset"]:
            fail(f"(g) `{f}` ถูก import ({len(imported_by[f])}) แต่ไม่มี ASSET role (live dep เสี่ยง archive)")
    # (c) required fields non-empty
    for cid, fields in claims.items():
        for r in REQUIRED:
            if not fields.get(r):
                fail(f"(c) {cid} field `{r}` หาย/ว่าง")
    # (j) [status-token invariant] `status:` ต้องขึ้นต้นด้วย disposition token — enforce P4
    #     กัน false-negative เงียบของ (h)/(i): status ผิดรูปแบบ = claim ถูกมองเป็น live โดยไม่มีเสียง
    for cid, fields in claims.items():
        stt = fields.get("status", "")          # .get — claim ที่ status หาย (c) รายงานอยู่แล้ว (CRITICAL-1)
        tok = leading_token(stt)
        if tok is None:
            fail(f"(j) {cid} status ไม่ขึ้นต้นด้วย disposition token {'/'.join(STATUS_TOKENS)}: `{stt}`")
        elif tok == "superseded" and not SUP_TGT.search(stt):
            fail(f"(j) {cid} superseded แต่ไม่มี →CLAIM-target ใน status: `{stt}`")
    # (b) reproduce resolve → script path จริง
    for cid, fields in claims.items():
        for tok in re.findall(r"Scripts/([A-Za-z_]\w*)\.py", fields.get("reproduce", "")):
            if not (scripts_dir / f"{tok}.py").exists():
                fail(f"(b) {cid} reproduce ชี้ Scripts/{tok}.py ที่ไม่มีจริง")
    # (e) script-index EXPERIMENT→CLAIM + claim-internal Claim-ID → resolve
    for f, meta in index.items():
        if meta["claim"] and meta["claim"] not in claims:
            fail(f"(e) `{f}` EXPERIMENT→{meta['claim']} แต่ claim block ไม่มี")
    for cid, fields in claims.items():
        for ref in CLAIMID_RE.findall(fields.get("status", "") + " " + fields.get("dependencies", "")):
            if ref not in claims:
                fail(f"(e) {cid} อ้าง {ref} (status/dependencies) แต่ไม่มี block นั้น (dangling)")
    # (d) frontier/carried Claim-ID → resolve
    for ref in fc_refs:
        if ref not in claims:
            fail(f"(d) FRONTIER/CARRIED อ้าง {ref} แต่ claim block ไม่มี")
    # (h) [cite-convention] frontier/carried cite ของ claim ที่ status ≠ live ต้องมี annotation
    #     (→superseded / DEAD / =live fact-level escape) — กัน bare superseded-cite หลอก owner (mechanize convention · ไม่พึ่ง prose)
    head = text.split("## SCRIPT INDEX")[0]
    for br in re.findall(r"\[CLAIM-\d{4}[^\]]*\]", head):
        for cid in CLAIMID_RE.findall(br):
            st = claims.get(cid, {}).get("status", "")
            # (P4 → enforced by check j) leading disposition token · parse ผ่าน leading_token จุดเดียว
            # substring เดิม false-flag "terminal (…superseded-by-…)" / single parser prevents predicate drift
            if leading_token(st) in NONLIVE:
                if not ("→" in br or "dead" in br.lower() or "=live" in br.lower()):
                    fail(f"(h) {cid} (status non-live) cite bare ใน frontier/carried `{br}` — ต้อง annotate (→N/DEAD/=live)")
    # (i) [arrow-target consistency · TRUE invariant] superseded cite ที่มี →target ต้องตรง status-target (SSOT = status field)
    #     (F3) check (h)/(i) scan เฉพาะ bracketed `[CLAIM-…]` · unbracketed slip = rare (convention = bracketed)
    for br in re.findall(r"\[CLAIM-\d{4}[^\]]*\]", head):
        if "=live" in br or "·mag" in br:            # fact-level escape = human-review → skip ทั้ง bracket ก่อน per-cid
            continue
        for cid in CLAIMID_RE.findall(br):
            st_raw = claims.get(cid, {}).get("status", "")
            if leading_token(st_raw) != "superseded":   # superseded-ONLY (กัน [CLAIM-0008 DEAD] false-positive) · parser เดียวกับ (h)/(j)
                continue
            stgt = SUP_TGT.search(st_raw)             # parse target จาก status field (SSOT)
            cm = re.search(r"→(\d{4})", br)           # cite arrow-target
            if not cm:
                fail(f"(i) {cid} superseded แต่ cite ไม่มี arrow-target: `{br}`")
            elif stgt and cm.group(1) != stgt.group(1):
                fail(f"(i) {cid} cite →{cm.group(1)} แต่ status →{stgt.group(1)} — แก้เป็น →{stgt.group(1)}")


# ─────────────────────────── self-test (fixtures + golden) ───────────────────────────
def _write(d, name, body):
    (d / f"{name}.py").write_text(body, encoding="utf-8")


def self_test():
    import tempfile
    passed = []

    def run_case(desc, build_fn, expect_substr, expect_present=True):
        # expect_present=False = negative-assert (error ต้อง "ไม่" fire) — regression guard ของ F1
        nonlocal_errors = ERRORS[:]
        ERRORS.clear()
        with tempfile.TemporaryDirectory() as td:
            sd = Path(td) / "Scripts"
            sd.mkdir()
            plan = Path(td) / "Plan"
            plan.mkdir()
            led = plan / "TRELLIS-010_LEDGER.md"
            build_fn(sd, led)
            validate(sd, led)
            found = any(expect_substr in e for e in ERRORS)
            hit = found if expect_present else not found
            passed.append((desc, hit, list(ERRORS)))
        ERRORS.clear()
        ERRORS.extend(nonlocal_errors)

    good_claim = ("### CLAIM-0001\n" + "\n".join(
        f"- **{f}:** x" for f in REQUIRED)
        .replace("status:** x", "status:** terminal")   # template "valid claim" ต้องสะอาดใต้ (j) — กัน latent mask (MAJOR-1)
        .replace("reproduce:** x", "reproduce:** python Scripts/a.py") + "\n")

    # (i) field หาย → (c) FAIL
    def fx_i(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        led.write_text("## SCRIPT INDEX\n- `a` :: ASSET\n## CLAIMS\n### CLAIM-0001\n- **observed:** x\n", encoding="utf-8")
    run_case("(i) missing-field→(c)", fx_i, "(c) CLAIM-0001")

    # (ii) frontier อ้าง Claim ไม่มี → (d) FAIL
    def fx_ii(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        led.write_text("## FRONTIER\nsee CLAIM-0099\n## SCRIPT INDEX\n- `a` :: ASSET\n", encoding="utf-8")
    run_case("(ii) dangling-frontier→(d)", fx_ii, "(d) FRONTIER")

    # (iii) script ไม่มี role → (a) FAIL
    def fx_iii(sd, led):
        _write(sd, "a", "x = 1\n")
        led.write_text("## SCRIPT INDEX\n- `a` :: \n", encoding="utf-8")
    run_case("(iii) no-role→(a)", fx_iii, "(a) cover: `a` ไม่มี role")

    # (iv) __main__ แต่ไม่มี EXPERIMENT → (f) FAIL
    def fx_iv(sd, led):
        _write(sd, "a", "if __name__ == '__main__':\n    print(1)\n")
        led.write_text("## SCRIPT INDEX\n- `a` :: ASSET\n", encoding="utf-8")
    run_case("(iv) main-no-disp→(f)", fx_iv, "(f) `a`")

    # (v) imported แต่ไม่มี ASSET → (g) FAIL
    def fx_v(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        _write(sd, "b", "import a\nif __name__ == '__main__':\n    a.f()\n")
        led.write_text("## SCRIPT INDEX\n- `a` :: EXPERIMENT=legacy→ARCHIVE\n- `b` :: EXPERIMENT=live→CLAIM-0001\n## CLAIMS\n" + good_claim, encoding="utf-8")
    run_case("(v) imported-no-asset→(g)", fx_v, "(g) `a`")

    # (vi) frontier cite superseded claim แบบ bare → (h) FAIL
    def fx_vi(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        sup = ("### CLAIM-0001\n" + "\n".join(f"- **{f}:** x" for f in REQUIRED)
               .replace("status:** x", "status:** superseded→CLAIM-0001")   # target ครบ กัน (j2) ปน · self-ref กัน (e)
               .replace("reproduce:** x", "reproduce:** python Scripts/a.py") + "\n")
        led.write_text("## FRONTIER\nดู [CLAIM-0001]\n## SCRIPT INDEX\n- `a` :: ASSET\n## CLAIMS\n" + sup, encoding="utf-8")
    run_case("(vi) bare-superseded-cite→(h)", fx_vi, "(h) CLAIM-0001")

    # (vii) frontier cite arrow-target ไม่ตรง status-target → (i) mismatch FAIL
    def fx_vii(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        sup = ("### CLAIM-0001\n" + "\n".join(f"- **{f}:** x" for f in REQUIRED)
               .replace("status:** x", "status:** superseded→CLAIM-0001")   # self-ref กัน (e) dangling
               .replace("reproduce:** x", "reproduce:** python Scripts/a.py") + "\n")
        led.write_text("## FRONTIER\nดู [CLAIM-0001→9999]\n## SCRIPT INDEX\n- `a` :: ASSET\n## CLAIMS\n" + sup, encoding="utf-8")
    run_case("(vii) arrow-target-mismatch→(i)", fx_vii, "(i) CLAIM-0001 cite →9999")

    # (viii) frontier cite superseded แบบ arrow ว่าง → (i) empty-arrow FAIL
    def fx_viii(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        sup = ("### CLAIM-0001\n" + "\n".join(f"- **{f}:** x" for f in REQUIRED)
               .replace("status:** x", "status:** superseded→CLAIM-0001")   # target ครบ กัน (j2) ปน · cite ว่างยัง fire (i)
               .replace("reproduce:** x", "reproduce:** python Scripts/a.py") + "\n")
        led.write_text("## FRONTIER\nดู [CLAIM-0001→]\n## SCRIPT INDEX\n- `a` :: ASSET\n## CLAIMS\n" + sup, encoding="utf-8")
    run_case("(viii) empty-arrow→(i)", fx_viii, "(i) CLAIM-0001 superseded แต่ cite ไม่มี arrow-target")

    # (ix) [F1 regression guard · negative-assert] terminal ที่ "มีคำ superseded ข้างใน" cite bare → (h) ต้องไม่ fire
    #      (ใต้ substring เก่าจะ fire = จับ revert startswith→substring ได้)
    def fx_ix(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        term = ("### CLAIM-0001\n" + "\n".join(f"- **{f}:** x" for f in REQUIRED)
                .replace("status:** x", "status:** terminal (v2 superseded-by-CLAIM-0001)")   # self-ref กัน (e) dangling
                .replace("reproduce:** x", "reproduce:** python Scripts/a.py") + "\n")
        led.write_text("## FRONTIER\nดู [CLAIM-0001]\n## SCRIPT INDEX\n- `a` :: ASSET\n## CLAIMS\n" + term, encoding="utf-8")
    run_case("(ix) terminal-w-superseded-substr NOT→(h)", fx_ix, "(h) CLAIM-0001", expect_present=False)

    # (x) [(j1)] status ไม่ lead ด้วย disposition token → (j) FAIL (เคส false-negative เงียบที่ P4 เตือน)
    def fx_x(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        bad = ("### CLAIM-0001\n" + "\n".join(f"- **{f}:** x" for f in REQUIRED)
               .replace("status:** x", "status:** re-measured, superseded→CLAIM-0001")   # self-ref กัน (e)
               .replace("reproduce:** x", "reproduce:** python Scripts/a.py") + "\n")
        led.write_text("## SCRIPT INDEX\n- `a` :: ASSET\n## CLAIMS\n" + bad, encoding="utf-8")
    run_case("(x) non-leading-token→(j1)", fx_x, "(j) CLAIM-0001 status ไม่ขึ้นต้นด้วย disposition token")

    # (xi) [(j2)] superseded ไร้ →target ใน status + ไม่ถูก cite ใน frontier ((i) จับไม่ได้) → (j) FAIL
    def fx_xi(sd, led):
        _write(sd, "a", "def f():\n    pass\n")
        sup = ("### CLAIM-0001\n" + "\n".join(f"- **{f}:** x" for f in REQUIRED)
               .replace("status:** x", "status:** superseded")
               .replace("reproduce:** x", "reproduce:** python Scripts/a.py") + "\n")
        led.write_text("## SCRIPT INDEX\n- `a` :: ASSET\n## CLAIMS\n" + sup, encoding="utf-8")
    run_case("(xi) superseded-no-target→(j2)", fx_xi, "(j) CLAIM-0001 superseded แต่ไม่มี →CLAIM-target")

    # golden-fixture: synthetic tree hand-audit — scan-logic ต้องตรง ground-truth (pin อิสระจาก emit)
    #   exotic syntax: no-space __main__ · multiline from-import · dynamic __import__(stdlib) · import a,b
    with tempfile.TemporaryDirectory() as td:
        sd = Path(td) / "Scripts"
        sd.mkdir()
        _write(sd, "lib1", "def a():\n    pass\n")                                    # ASSET-only (no main, imported)
        _write(sd, "lib2", "def b():\n    pass\n")                                    # ASSET-only (imported via multi/multiline)
        _write(sd, "expA", "import lib1, os\nif __name__=='__main__':\n    lib1.a()\n")  # DUAL: no-space main + import a,b
        _write(sd, "expB", "from lib2 import (\n    b,\n)\nx=__import__('pathlib')\nif __name__ == '__main__':\n    b()\n")  # DUAL: multiline-from + dynamic stdlib
        _write(sd, "solo", "if __name__ == '__main__':\n    print('x')\n")            # EXP-only (main, no importer)
        files, imported_by, has_main = scan(sd)
        gold_asset = {f for f in files if imported_by[f]}
        gold_main = has_main
        ok = (gold_asset == {"lib1", "lib2"} and gold_main == {"expA", "expB", "solo"}
              and imported_by["lib1"] == {"expA"} and imported_by["lib2"] == {"expB"})
        passed.append(("golden scan-logic (exotic syntax)", ok, [f"asset={sorted(gold_asset)} main={sorted(gold_main)}"]))

    print("=== ledger_check self-test ===")
    allok = True
    for desc, hit, errs in passed:
        mark = "PASS" if hit else "FAIL"
        if not hit:
            allok = False
        print(f"  [{mark}] {desc}" + ("" if hit else f"  <-- {errs}"))
    # count = derived จาก runtime (SSOT) — ห้าม hardcode "N fixture" ใน prose ที่ไหน (F2)
    n_gold = sum(1 for d, _, _ in passed if d.startswith("golden"))
    print(f"self-test: {len(passed) - n_gold} fixtures + {n_gold} golden")
    print("ALL PASS" if allok else "SELF-TEST FAILED")
    return 0 if allok else 1


def main(argv):
    if "--self-test" in argv:
        return self_test()
    if "--emit-index" in argv:
        print(emit_index(ROOT))
        return 0
    validate(ROOT, LEDGER)
    if ERRORS:
        print(f"LEDGER CHECK FAIL ({len(ERRORS)}):", file=sys.stderr)
        for e in ERRORS:
            print("  - " + e, file=sys.stderr)
        return 1
    print("LEDGER CHECK PASS")
    return 0


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    sys.exit(main(sys.argv[1:]))
